### ISSUE TITLE
Cassowary in pure C and Lua

### ISSUE THREAD

**Issue by starwing** [Overconstrained/Overconstrained#8]
Hi,

I have made a new implement that a single-file library in Clean C (cross set of ANSI C89 and C++), and a Lua binding, here: https://github.com/starwing/amoeba

reviews and feedbacks are welcome :)

**Comment by hfossli** [comment]
Thanks! I'll add this to overconstrained.io asap (probably on monday). :-)

I think it looks great. The fact that it is a stb library in c makes it
very convenient and I would like to see wrappers around this in other
languages. I know they have some performance problems in java so it would
be interesting to see the effect of wrapping this library.
la. 18. juni 2016 kl. 20:55 skrev Xavier Wang notifications@github.com:

**Comment by starwing** [comment]
Thanks:)

I have not implement stay variable, as I don't know it's real usage. amoeba always optimize and dual_optimize rows, and always update variables. So no need call resolve to set stay variable. maybe I should make options to not always update and optimize variables and rows?

If a clear usage can be offered, I may implement the stay variable, or make all non-edit variable satiable.

**Comment by hfossli** [comment]
I wouldn't bother implementing stays. I'm not the right guy to discuss
cassowary papers with :) join us on Slack and you'll find many people
familiar with the internals :)
la. 18. juni 2016 kl. 22:08 skrev Xavier Wang notifications@github.com:

**Comment by hfossli** [comment]
Added to overconstrained.io btw!

**Comment by starwing** [comment]
thanks :-)
