### ISSUE TITLE
Link to Objc AutoLayout is broken

### ISSUE THREAD

**Issue by kostiakoval** [Overconstrained/Overconstrained#9]
![screen shot 2016-06-21 at 13 27 32](https://cloud.githubusercontent.com/assets/1086260/16227914/eeeb11dc-37b3-11e6-98ed-48141d6b6ce7.png)
Link: 
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/AutolayoutPG/Introduction/Introduction.html

Correct links: 
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/AutolayoutPG/index.html

**Comment by hfossli** [comment]
Thanks. Fixed in https://github.com/Overconstrained/Overconstrained/commit/193ea6c7d9951d7269e99e0f13adbc38d9484875.
